apiVersion: v1
kind: Service
metadata:
  name: {{ include "tools.service.headless" . | quote }}
  namespace: {{ include "tools.namespace" . | quote }}
  labels: {{ include "tools.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tools.commonannotations" . | nindent 4 }}
  {{- end }}
spec:
  selector: {{ include "tools.selectorLabels" . | nindent 4 }}
    componentName: {{ include "tools.master.name" . | quote }}
  clusterIP: None
  ports:
    - name: tcp-client
      port: {{ .Values.service.ports.client }}
      targetPort: client
    - name: tcp-follower
      port: {{ .Values.service.ports.follower }}
      targetPort: follower
    - name: tcp-election
      port: {{ .Values.service.ports.election }}
      targetPort: election