apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zk-cm
data:
  zoo.cfg: |
    initLimit=10
    syncLimit=5
    tickTime=2000
    dataDir=/opt/zookeeper/data
    dataLogDir=/opt/zookeeper/log
    clientPort=2181
    autopurge.snapRetainCount=30
    autopurge.purgeInterval=24
    4lw.commands.whitelist=*
    dynamicConfigFile=/opt/zookeeper/data/conf/zoo_replicated1.cfg.dynamic
  logback.xml: |
    <configuration>
    <property name="zookeeper.console.threshold" value="INFO" />

    <property name="zookeeper.log.dir" value="." />
    <property name="zookeeper.log.file" value="zookeeper.log" />
    <property name="zookeeper.log.threshold" value="INFO" />
    <property name="zookeeper.log.maxfilesize" value="256MB" />
    <property name="zookeeper.log.maxbackupindex" value="20" />

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
        <pattern>%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
        <level>${zookeeper.console.threshold}</level>
        </filter>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
    </root>
    </configuration>