apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tools.disruption.budget" . | quote }}
  namespace: {{ include "tools.namespace" . | quote }}
  labels: {{ include "tools.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tools.commonannotations" . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{ include "tools.selectorLabels" . | indent 6  | trim }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}